name: cardia_satellite_pro
description: Professional Satellite Encryption System.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  local_auth: ^2.1.6
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4

flutter:
  uses-material-design: true
