name: secure_chat_v2
description: Cardia Hybrid Engine (DTN + Offline).
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  intl: ^0.19.0
  uuid: ^4.2.1
flutter:
  uses-material-design: true
