name: secure_chat_app
description: A secure encrypted chat application.
version: 1.0.0+1
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  encrypt: ^5.0.3
  local_auth: ^2.1.6
  swipe_to: ^1.0.2
  translator: ^0.1.7
  glass_kit: ^4.0.2
  avatar_glow: ^3.0.1
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
